num = int(input('Enter 1st number:'))
num2 = int(input('Enter 2nd number:'))
num3 = int(input('Enter 3rd number:'))
num4 = int(input('Enter 4th number:'))
if num > num2 > num3 > num4: print(num , num2 , num3, num4)
if num > num3 > num2 > num4: print(num , num3 , num2, num4)
if num2 > num > num3  > num4: print(num2 , num , num3, num4)
if num2 > num3 > num > num4: print(num2 , num3 , num, num4)
if num3 > num2 > num > num4: print(num3 , num2 , num, num4)
if num3 > num > num2 >num4: print(num3, num, num2, num4)
if num4 > num > num2 >num3: print(num3, num, num2,num4)
if num4 > num2 > num >num3: print(num4, num2, num, num3)
if num4 > num3 > num >num2: print(num4, num3, num, num2)
if num4 > num2 > num3 >num: print(num4, num2, num3, num)
if num3 > num4 > num2 >num: print(num3, num4, num2, num)

# ЕЩЕ МОЖНО БЫЛО МНОГО ПИСАТЬ НОЯ НЕ СТАЛ. ИЗЗА ТОГО ЧТО ВЫ ПОЩИТАЕТЕ ЕГО ПЛОХИМ КОДОМ
